version: '3.7'

services:
  mysql_db:
    container_name: adminjs-example-mysql
    image: mysql
    environment:
      MYSQL_USER: adminjs
      MYSQL_PASSWORD: adminjs
      MYSQL_ROOT_PASSWORD: adminjs
      MYSQL_DATABASE: adminjs
    ports:
      - "3308:3306"
    volumes:
      - /mysql_db_example_app:/var/lib/mysql

volumes:
  mysql_db_example_app:
